from __future__ import annotations

import html
import json
from collections import Counter
from pathlib import Path

from .duplicates import DuplicateSummary
from .scoring import AuditConfig, Recommendation


def write_summary(
    path: Path,
    recommendations: list[Recommendation],
    config: AuditConfig | None = None,
    source_labels: list[str] | None = None,
    duplicate_summary: DuplicateSummary | None = None,
) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    config = config or AuditConfig()
    source_labels = source_labels or []
    buckets = Counter(rec.bucket for rec in recommendations)
    tags = Counter(rec.tag for rec in recommendations)
    ranks = Counter(rec.rank for rec in recommendations)
    kinds = Counter(rec.kind for rec in recommendations)
    lines = [
        "# Destiny Vault Audit Summary",
        "",
        "Generated by the local Destiny Vault Auditor prototype.",
        "",
        "## Audit Config",
        "",
    ]
    for key, value in config.summary.items():
        lines.append(f"- `{key}`: `{value}`")
    if source_labels:
        lines.extend(["", "## Source Inputs", ""])
        for label in source_labels:
            lines.append(f"- {label}")
    if duplicate_summary:
        lines.extend(
            [
                "",
                "## Duplicate Groups",
                "",
                f"- Groups: {duplicate_summary.groups}",
                f"- Items in duplicate groups: {duplicate_summary.items}",
                f"- Weapon groups: {duplicate_summary.weapon_groups}",
                f"- Armor groups: {duplicate_summary.armor_groups}",
            ]
        )
    lines.extend(
        [
            "",
            "## Counts",
            "",
            f"- Items reviewed: {len(recommendations)}",
            f"- Item kinds: {', '.join(f'{kind} {count}' for kind, count in sorted(kinds.items()))}",
            f"- Proposed tags: {', '.join(f'{tag} {count}' for tag, count in sorted(tags.items()))}",
            f"- Review ranks: {', '.join(f'{rank} {count}' for rank, count in sorted(ranks.items()))}",
            "",
            "## Buckets",
            "",
        ]
    )
    for bucket, count in buckets.most_common():
        lines.append(f"- `{bucket}`: {count}")
    lines.extend(["", "## Recommendations", ""])
    for rec in recommendations:
        lines.append(f"- `{rec.tag}` `{rec.bucket}` **{rec.name}** - {rec.reason}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_decisions(
    path: Path,
    recommendations: list[Recommendation],
    config: AuditConfig | None = None,
    source_labels: list[str] | None = None,
) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    config = config or AuditConfig()
    payload = {
        "schema": "destiny-vault-auditor.decisions.v1",
        "config": config.summary,
        "sources": source_labels or [],
        "recommendations": [rec.__dict__ | {"comment": rec.comment} for rec in recommendations],
    }
    path.write_text(json.dumps(payload, indent=2), encoding="utf-8")


def write_html(
    path: Path,
    recommendations: list[Recommendation],
    config: AuditConfig | None = None,
    source_labels: list[str] | None = None,
    duplicate_summary: DuplicateSummary | None = None,
) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    config = config or AuditConfig()
    source_labels = source_labels or []
    duplicate_summary = duplicate_summary or DuplicateSummary()
    data = [rec.__dict__ | {"comment": rec.comment} for rec in recommendations]
    payload = json.dumps(data)
    config_payload = json.dumps(config.summary)
    sources_payload = json.dumps(source_labels)
    bucket_options = sorted({rec.bucket for rec in recommendations})
    kind_options = sorted({rec.kind for rec in recommendations})
    rank_options = sorted({rec.rank for rec in recommendations if rec.rank})
    tag_options = sorted({rec.tag for rec in recommendations} | {"archive", "favorite", "junk", "keep"})
    html_text = f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Destiny Vault Auditor Review</title>
  <style>
    :root {{ color-scheme: dark; font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }}
    body {{ margin: 0; background: #11100d; color: #f1eee8; }}
    header {{ padding: 24px 28px 12px; border-bottom: 1px solid #373026; background: #181510; position: sticky; top: 0; z-index: 2; }}
    h1 {{ margin: 0 0 14px; font-size: 24px; }}
    .preflight {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(170px, 1fr)); gap: 8px; margin: 0 0 14px; }}
    .config-chip {{ background: #211d16; border: 1px solid #3e3529; border-radius: 8px; padding: 8px 10px; }}
    .config-chip span {{ display: block; color: #a79b8c; font-size: 11px; text-transform: uppercase; letter-spacing: .05em; }}
    .config-chip strong {{ display: block; margin-top: 2px; font-size: 14px; }}
    .controls {{ display: flex; flex-wrap: wrap; gap: 10px; align-items: center; }}
    input, select, button {{ background: #242018; color: #f1eee8; border: 1px solid #4c4234; border-radius: 6px; padding: 8px 10px; }}
    button {{ cursor: pointer; }}
    main {{ padding: 18px 28px 40px; }}
    .stats {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 10px; margin-bottom: 16px; }}
    .stat {{ background: #1b1812; border: 1px solid #373026; border-radius: 8px; padding: 12px; }}
    .stat strong {{ display: block; font-size: 22px; }}
    .duplicate-panel {{ margin-bottom: 18px; }}
    .duplicate-panel h2 {{ margin: 0 0 10px; font-size: 17px; }}
    .duplicate-panel p {{ margin: 0 0 10px; color: #bdae9b; }}
    table {{ width: 100%; border-collapse: collapse; background: #17140f; border: 1px solid #373026; }}
    th, td {{ padding: 10px; border-bottom: 1px solid #302a22; text-align: left; vertical-align: top; }}
    th {{ color: #cfc4b5; font-size: 12px; text-transform: uppercase; letter-spacing: .06em; background: #1d1912; position: sticky; top: 151px; }}
    tr[data-bucket="replace-now"], tr[data-bucket="junk"] {{ background: #241312; }}
    tr[data-bucket="keep-refarm"] {{ background: #221d10; }}
    tr[data-bucket="protect"] {{ background: #111d18; }}
    .pill {{ display: inline-block; border: 1px solid #5a4c3c; border-radius: 999px; padding: 2px 8px; font-size: 12px; color: #e6d6bd; }}
    .reason {{ color: #d4c8b8; max-width: 720px; }}
    .muted {{ color: #a79b8c; }}
    .signals {{ margin-top: 5px; display: flex; flex-wrap: wrap; gap: 5px; }}
    .signal {{ border: 1px solid #473d31; border-radius: 999px; padding: 1px 6px; font-size: 11px; color: #bdae9b; }}
    .tag-edit {{ min-width: 96px; }}
    .comment-edit {{ margin-top: 8px; width: min(100%, 760px); min-height: 62px; resize: vertical; font: inherit; line-height: 1.35; background: #14110d; color: #f1eee8; border: 1px solid #3e3529; border-radius: 6px; padding: 8px; }}
  </style>
</head>
<body>
  <header>
    <h1>Destiny Vault Auditor Review</h1>
    <section class="preflight" id="preflight"></section>
    <div class="controls">
      <input id="search" type="search" placeholder="Search weapons or reasons">
      <select id="kind"><option value="">All gear</option>{''.join(f'<option>{html.escape(kind)}</option>' for kind in kind_options)}</select>
      <select id="rank"><option value="">All ranks</option>{''.join(f'<option>{html.escape(rank)}</option>' for rank in rank_options)}</select>
      <select id="bucket"><option value="">All buckets</option>{''.join(f'<option>{html.escape(bucket)}</option>' for bucket in bucket_options)}</select>
      <select id="tag"><option value="">All tags</option>{''.join(f'<option>{html.escape(tag)}</option>' for tag in tag_options)}</select>
      <button id="export">Export decisions JSON</button>
    </div>
  </header>
  <main>
    <section class="stats" id="stats"></section>
    <section class="duplicate-panel" id="duplicates"></section>
    <table>
      <thead>
        <tr><th>Name</th><th>Bucket</th><th>Tag</th><th>Confidence</th><th>Reason</th></tr>
      </thead>
      <tbody id="rows"></tbody>
    </table>
  </main>
  <script>
    const recommendations = {payload};
    const config = {config_payload};
    const sources = {sources_payload};
    const duplicateSummary = {json.dumps(duplicate_summary.__dict__)};
    const tagOptions = {json.dumps(tag_options)};
    const rowsEl = document.getElementById('rows');
    const searchEl = document.getElementById('search');
    const kindEl = document.getElementById('kind');
    const rankEl = document.getElementById('rank');
    const bucketEl = document.getElementById('bucket');
    const tagEl = document.getElementById('tag');
    const statsEl = document.getElementById('stats');
    const preflightEl = document.getElementById('preflight');
    const duplicatesEl = document.getElementById('duplicates');

    function renderPreflight() {{
      const labels = [
        ['cleanup_mode', 'Cleanup mode'],
        ['high_level_threshold', 'High level protect'],
        ['locked_behavior', 'Locked items'],
        ['old_vs_new', 'Old vs new'],
        ['pvp_caution', 'PvP caution'],
        ['low_power_below', 'Low power note']
      ];
      if (sources.length) labels.push(['__sources', 'Sources']);
      preflightEl.innerHTML = labels.map(([key, label]) => `
        <div class="config-chip"><span>${{escapeHtml(label)}}</span><strong>${{escapeHtml(key === '__sources' ? sources.join(', ') : config[key])}}</strong></div>
      `).join('');
    }}

    function renderStats(items) {{
      const counts = new Map();
      for (const rec of items) counts.set(rec.bucket, (counts.get(rec.bucket) || 0) + 1);
      statsEl.innerHTML = Array.from(counts.entries())
        .sort((a, b) => b[1] - a[1])
        .map(([bucket, count]) => `<div class="stat"><strong>${{count}}</strong><span>${{bucket}}</span></div>`)
        .join('');
    }}

    function renderDuplicates() {{
      const groups = new Map();
      for (const rec of recommendations) {{
        if (!rec.duplicate_group) continue;
        if (!groups.has(rec.duplicate_group)) groups.set(rec.duplicate_group, []);
        groups.get(rec.duplicate_group).push(rec);
      }}
      if (!groups.size) {{
        duplicatesEl.innerHTML = '';
        return;
      }}
      const rows = Array.from(groups.entries()).map(([group, items]) => {{
        const best = items.find(item => item.duplicate_role === 'best') || items[0];
        const copies = items.filter(item => item.duplicate_role !== 'best');
        return `
          <tr>
            <td><strong>${{escapeHtml(best.duplicate_group_label || group)}}</strong><div class="muted">${{escapeHtml(group)}} · ${{items.length}} items</div></td>
            <td>${{escapeHtml(best.name)}}<div class="muted">${{escapeHtml(best.bucket)}} · ${{escapeHtml(best.tag)}}</div></td>
            <td>${{copies.map(copy => `${{escapeHtml(copy.name)}} <span class="muted">(${{escapeHtml(copy.bucket)}} · ${{escapeHtml(copy.tag)}})</span>`).join('<br>')}}</td>
          </tr>`;
      }}).join('');
      duplicatesEl.innerHTML = `
        <h2>Duplicate Queue</h2>
        <p>${{duplicateSummary.groups}} groups · ${{duplicateSummary.items}} items. The auditor keeps a best copy visible before suggesting cleanup for weaker copies.</p>
        <table>
          <thead><tr><th>Group</th><th>Best Current Copy</th><th>Other Copies</th></tr></thead>
          <tbody>${{rows}}</tbody>
        </table>`;
    }}

    function matches(rec) {{
      const query = searchEl.value.trim().toLowerCase();
      if (kindEl.value && rec.kind !== kindEl.value) return false;
      if (rankEl.value && rec.rank !== rankEl.value) return false;
      if (bucketEl.value && rec.bucket !== bucketEl.value) return false;
      if (tagEl.value && rec.tag !== tagEl.value) return false;
      if (!query) return true;
      return [rec.name, rec.kind, rec.reason, rec.comment, rec.bucket, rec.tag, rec.rank, ...(rec.signals || [])].join(' ').toLowerCase().includes(query);
    }}

    function render() {{
      const visible = recommendations
        .map((rec, index) => ({{rec, index}}))
        .filter(({{rec}}) => matches(rec));
      renderStats(visible.map(({{rec}}) => rec));
      rowsEl.innerHTML = visible.map(({{rec, index}}) => `
        <tr data-bucket="${{rec.bucket}}">
          <td><strong>${{escapeHtml(rec.name)}}</strong><div class="muted">${{escapeHtml(rec.kind)}} · ${{escapeHtml(rec.item_id)}}</div></td>
          <td><span class="pill">${{escapeHtml(rec.bucket)}}</span><div class="muted">${{escapeHtml(rec.rank)}}</div></td>
          <td><select class="tag-edit" data-index="${{index}}">${{tagOptions.map(tag => `<option value="${{escapeHtml(tag)}}" ${{tag === rec.tag ? 'selected' : ''}}>${{escapeHtml(tag)}}</option>`).join('')}}</select></td>
          <td>${{escapeHtml(rec.confidence)}}</td>
          <td class="reason">${{escapeHtml(rec.reason)}}<div class="muted">${{escapeHtml((rec.sources || []).join(', '))}}</div><div class="signals">${{(rec.signals || []).map(signal => `<span class="signal">${{escapeHtml(signal)}}</span>`).join('')}}</div><textarea class="comment-edit" data-index="${{index}}">${{escapeHtml(rec.comment)}}</textarea></td>
        </tr>`).join('');
      for (const select of document.querySelectorAll('.tag-edit')) {{
        select.addEventListener('change', event => {{
          const rec = recommendations[Number(event.currentTarget.dataset.index)];
          rec.tag = event.currentTarget.value;
          if (!rec.signals.includes('reviewed-decision')) rec.signals.push('reviewed-decision');
        }});
      }}
      for (const textarea of document.querySelectorAll('.comment-edit')) {{
        textarea.addEventListener('input', event => {{
          const rec = recommendations[Number(event.currentTarget.dataset.index)];
          rec.comment = event.currentTarget.value;
          rec.comment_override = event.currentTarget.value;
          if (!rec.signals.includes('reviewed-decision')) rec.signals.push('reviewed-decision');
        }});
      }}
    }}

    function escapeHtml(value) {{
      return String(value ?? '').replace(/[&<>"']/g, c => ({{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}}[c]));
    }}

    for (const el of [searchEl, kindEl, rankEl, bucketEl, tagEl]) el.addEventListener('input', render);
    document.getElementById('export').addEventListener('click', () => {{
      const blob = new Blob([JSON.stringify({{schema: 'destiny-vault-auditor.review.v1', config, sources, recommendations}}, null, 2)], {{type: 'application/json'}});
      const url = URL.createObjectURL(blob);
      const a = Object.assign(document.createElement('a'), {{href: url, download: 'decisions.json'}});
      a.click();
      URL.revokeObjectURL(url);
    }});
    renderPreflight();
    renderDuplicates();
    render();
  </script>
</body>
</html>
"""
    path.write_text(html_text, encoding="utf-8")
