from __future__ import annotations

import html
import json
from collections import Counter
from pathlib import Path

from .scoring import AuditConfig, Recommendation


def write_summary(path: Path, recommendations: list[Recommendation], config: AuditConfig | None = None) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    config = config or AuditConfig()
    buckets = Counter(rec.bucket for rec in recommendations)
    tags = Counter(rec.tag for rec in recommendations)
    ranks = Counter(rec.rank for rec in recommendations)
    lines = [
        "# Destiny Vault Audit Summary",
        "",
        "Generated by the local Destiny Vault Auditor prototype.",
        "",
        "## Audit Config",
        "",
    ]
    for key, value in config.summary.items():
        lines.append(f"- `{key}`: `{value}`")
    lines.extend(
        [
            "",
            "## Counts",
            "",
            f"- Items reviewed: {len(recommendations)}",
            f"- Proposed tags: {', '.join(f'{tag} {count}' for tag, count in sorted(tags.items()))}",
            f"- Review ranks: {', '.join(f'{rank} {count}' for rank, count in sorted(ranks.items()))}",
            "",
            "## Buckets",
            "",
        ]
    )
    for bucket, count in buckets.most_common():
        lines.append(f"- `{bucket}`: {count}")
    lines.extend(["", "## Recommendations", ""])
    for rec in recommendations:
        lines.append(f"- `{rec.tag}` `{rec.bucket}` **{rec.name}** - {rec.reason}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_decisions(path: Path, recommendations: list[Recommendation], config: AuditConfig | None = None) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    config = config or AuditConfig()
    payload = {
        "schema": "destiny-vault-auditor.decisions.v1",
        "config": config.summary,
        "recommendations": [rec.__dict__ | {"comment": rec.comment} for rec in recommendations],
    }
    path.write_text(json.dumps(payload, indent=2), encoding="utf-8")


def write_html(path: Path, recommendations: list[Recommendation], config: AuditConfig | None = None) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    config = config or AuditConfig()
    data = [rec.__dict__ | {"comment": rec.comment} for rec in recommendations]
    payload = json.dumps(data)
    config_payload = json.dumps(config.summary)
    bucket_options = sorted({rec.bucket for rec in recommendations})
    rank_options = sorted({rec.rank for rec in recommendations if rec.rank})
    tag_options = sorted({rec.tag for rec in recommendations})
    html_text = f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Destiny Vault Auditor Review</title>
  <style>
    :root {{ color-scheme: dark; font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }}
    body {{ margin: 0; background: #11100d; color: #f1eee8; }}
    header {{ padding: 24px 28px 12px; border-bottom: 1px solid #373026; background: #181510; position: sticky; top: 0; z-index: 2; }}
    h1 {{ margin: 0 0 14px; font-size: 24px; }}
    .preflight {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(170px, 1fr)); gap: 8px; margin: 0 0 14px; }}
    .config-chip {{ background: #211d16; border: 1px solid #3e3529; border-radius: 8px; padding: 8px 10px; }}
    .config-chip span {{ display: block; color: #a79b8c; font-size: 11px; text-transform: uppercase; letter-spacing: .05em; }}
    .config-chip strong {{ display: block; margin-top: 2px; font-size: 14px; }}
    .controls {{ display: flex; flex-wrap: wrap; gap: 10px; align-items: center; }}
    input, select, button {{ background: #242018; color: #f1eee8; border: 1px solid #4c4234; border-radius: 6px; padding: 8px 10px; }}
    button {{ cursor: pointer; }}
    main {{ padding: 18px 28px 40px; }}
    .stats {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 10px; margin-bottom: 16px; }}
    .stat {{ background: #1b1812; border: 1px solid #373026; border-radius: 8px; padding: 12px; }}
    .stat strong {{ display: block; font-size: 22px; }}
    table {{ width: 100%; border-collapse: collapse; background: #17140f; border: 1px solid #373026; }}
    th, td {{ padding: 10px; border-bottom: 1px solid #302a22; text-align: left; vertical-align: top; }}
    th {{ color: #cfc4b5; font-size: 12px; text-transform: uppercase; letter-spacing: .06em; background: #1d1912; position: sticky; top: 151px; }}
    tr[data-bucket="replace-now"], tr[data-bucket="junk"] {{ background: #241312; }}
    tr[data-bucket="keep-refarm"] {{ background: #221d10; }}
    tr[data-bucket="protect"] {{ background: #111d18; }}
    .pill {{ display: inline-block; border: 1px solid #5a4c3c; border-radius: 999px; padding: 2px 8px; font-size: 12px; color: #e6d6bd; }}
    .reason {{ color: #d4c8b8; max-width: 720px; }}
    .muted {{ color: #a79b8c; }}
    .signals {{ margin-top: 5px; display: flex; flex-wrap: wrap; gap: 5px; }}
    .signal {{ border: 1px solid #473d31; border-radius: 999px; padding: 1px 6px; font-size: 11px; color: #bdae9b; }}
  </style>
</head>
<body>
  <header>
    <h1>Destiny Vault Auditor Review</h1>
    <section class="preflight" id="preflight"></section>
    <div class="controls">
      <input id="search" type="search" placeholder="Search weapons or reasons">
      <select id="rank"><option value="">All ranks</option>{''.join(f'<option>{html.escape(rank)}</option>' for rank in rank_options)}</select>
      <select id="bucket"><option value="">All buckets</option>{''.join(f'<option>{html.escape(bucket)}</option>' for bucket in bucket_options)}</select>
      <select id="tag"><option value="">All tags</option>{''.join(f'<option>{html.escape(tag)}</option>' for tag in tag_options)}</select>
      <button id="export">Export decisions JSON</button>
    </div>
  </header>
  <main>
    <section class="stats" id="stats"></section>
    <table>
      <thead>
        <tr><th>Name</th><th>Bucket</th><th>Tag</th><th>Confidence</th><th>Reason</th></tr>
      </thead>
      <tbody id="rows"></tbody>
    </table>
  </main>
  <script>
    const recommendations = {payload};
    const config = {config_payload};
    const rowsEl = document.getElementById('rows');
    const searchEl = document.getElementById('search');
    const rankEl = document.getElementById('rank');
    const bucketEl = document.getElementById('bucket');
    const tagEl = document.getElementById('tag');
    const statsEl = document.getElementById('stats');
    const preflightEl = document.getElementById('preflight');

    function renderPreflight() {{
      const labels = [
        ['cleanup_mode', 'Cleanup mode'],
        ['high_level_threshold', 'High level protect'],
        ['locked_behavior', 'Locked items'],
        ['old_vs_new', 'Old vs new'],
        ['pvp_caution', 'PvP caution'],
        ['low_power_below', 'Low power note']
      ];
      preflightEl.innerHTML = labels.map(([key, label]) => `
        <div class="config-chip"><span>${{escapeHtml(label)}}</span><strong>${{escapeHtml(config[key])}}</strong></div>
      `).join('');
    }}

    function renderStats(items) {{
      const counts = new Map();
      for (const rec of items) counts.set(rec.bucket, (counts.get(rec.bucket) || 0) + 1);
      statsEl.innerHTML = Array.from(counts.entries())
        .sort((a, b) => b[1] - a[1])
        .map(([bucket, count]) => `<div class="stat"><strong>${{count}}</strong><span>${{bucket}}</span></div>`)
        .join('');
    }}

    function matches(rec) {{
      const query = searchEl.value.trim().toLowerCase();
      if (rankEl.value && rec.rank !== rankEl.value) return false;
      if (bucketEl.value && rec.bucket !== bucketEl.value) return false;
      if (tagEl.value && rec.tag !== tagEl.value) return false;
      if (!query) return true;
      return [rec.name, rec.reason, rec.comment, rec.bucket, rec.tag, rec.rank, ...(rec.signals || [])].join(' ').toLowerCase().includes(query);
    }}

    function render() {{
      const visible = recommendations.filter(matches);
      renderStats(visible);
      rowsEl.innerHTML = visible.map(rec => `
        <tr data-bucket="${{rec.bucket}}">
          <td><strong>${{escapeHtml(rec.name)}}</strong><div class="muted">${{escapeHtml(rec.item_id)}}</div></td>
          <td><span class="pill">${{escapeHtml(rec.bucket)}}</span><div class="muted">${{escapeHtml(rec.rank)}}</div></td>
          <td>${{escapeHtml(rec.tag)}}</td>
          <td>${{escapeHtml(rec.confidence)}}</td>
          <td class="reason">${{escapeHtml(rec.reason)}}<div class="muted">${{escapeHtml((rec.sources || []).join(', '))}}</div><div class="signals">${{(rec.signals || []).map(signal => `<span class="signal">${{escapeHtml(signal)}}</span>`).join('')}}</div></td>
        </tr>`).join('');
    }}

    function escapeHtml(value) {{
      return String(value ?? '').replace(/[&<>"']/g, c => ({{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}}[c]));
    }}

    for (const el of [searchEl, rankEl, bucketEl, tagEl]) el.addEventListener('input', render);
    document.getElementById('export').addEventListener('click', () => {{
      const blob = new Blob([JSON.stringify({{schema: 'destiny-vault-auditor.review.v1', config, recommendations}}, null, 2)], {{type: 'application/json'}});
      const url = URL.createObjectURL(blob);
      const a = Object.assign(document.createElement('a'), {{href: url, download: 'decisions.json'}});
      a.click();
      URL.revokeObjectURL(url);
    }});
    renderPreflight();
    render();
  </script>
</body>
</html>
"""
    path.write_text(html_text, encoding="utf-8")
